sudo: false
language: go
go:
  - "1.8"
git:
    depth: 1
install: 
    - go get -v github.com/gohugoio/hugo
script:
    - hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: source
    local_dir: public
    repo: arjenzhou/arjenzhou.github.io
    fqdn: jcorn.cn
    target_branch: master
    email: zhouyang.zy@protonmail.com
    name: zhouyang
